<?xml version="1.0" encoding="UTF-8"?>

<messages overlay="false" product="BIMLMV" project="7.5.0.0" timestamp="1483545325588">
  <message id="BIMFV0002E" group="bimlmv" key="autodesk_api_err" prefix="false" options_value="129" displaymethod="MSGBOX" otherscrc="3959072221" valuecrc="4081827038" explanationcrc="0" responsecrc="0">
    <value>Error accessing the Autodesk cloud: {0} - {1}</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0003E" group="bimlmv" key="bad_checksum" prefix="false" options_value="129" displaymethod="MSGBOX" otherscrc="1167209548" valuecrc="3906075319" explanationcrc="1918527617" responsecrc="0">
    <value>Upload file checksum mismatch</value>
    <explanation>The checksum for the uploaded file reported by the Autodesk service does not match the local file checksum.  Try the upload again.</explanation>
    <response></response>
  </message>
  <message id="BIMFV0004E" group="bimlmv" key="No_object" prefix="false" options_value="0" displaymethod="MSGBOX" otherscrc="303391901" valuecrc="4067310516" explanationcrc="0" responsecrc="2164904364">
    <value>No objects created by the upload</value>
    <explanation></explanation>
    <response>Try the upload again</response>
  </message>
  <message id="BIMFV0005E" group="bimlmv" key="network-fault" prefix="true" options_value="129" displaymethod="MSGBOX" otherscrc="867591715" valuecrc="3443417924" explanationcrc="0" responsecrc="0">
    <value>&quot;An exception occurred while contacting the Autodesk cloud service&quot;</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0006I" group="bimlmv" key="no-delete-during-upload" prefix="false" options_value="1" displaymethod="MSGBOX" otherscrc="3484815999" valuecrc="1752109050" explanationcrc="0" responsecrc="0">
    <value>A model can&apos;t be delete while an upload is in progress</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0007I" group="bimlmv" key="TOOLBAR_HIDE_SELECTION" prefix="false" options_value="0" displaymethod="STATUS" otherscrc="1695409163" valuecrc="521877010" explanationcrc="0" responsecrc="0">
    <value>Hide selection</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0008I" group="bimlmv" key="TOOLBAR_SEARCH" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2356916829" valuecrc="3009207953" explanationcrc="0" responsecrc="0">
    <value>Search</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0009I" group="bimlmv" key="TOOLBAR_SELECTION_MODE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="400490034" valuecrc="4095202138" explanationcrc="0" responsecrc="0">
    <value>Set selection mode</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0010I" group="bimlmv" key="TOOLBAR_ZOOM_MODEL" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1474370854" valuecrc="1079814309" explanationcrc="0" responsecrc="0">
    <value>Zoom to model</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0011I" group="bimlmv" key="KEY_OF" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3427029321" valuecrc="124625402" explanationcrc="0" responsecrc="0">
    <value>of</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0012I" group="bimlnv" key="KEY_DASH" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3151659961" valuecrc="2547889144" explanationcrc="0" responsecrc="0">
    <value>-</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0013I" group="bimlmv" key="KEY_OPEN_FILTER" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="545247190" valuecrc="234646827" explanationcrc="0" responsecrc="0">
    <value>Open Filter</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0014I" group="bimlmv" key="KEY_CLOSE_FILTER" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1424434777" valuecrc="288910262" explanationcrc="0" responsecrc="0">
    <value>Close Filter</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0015I" group="bimlmv" key="KEY_FILTER_TABLE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3477236278" valuecrc="4229707601" explanationcrc="0" responsecrc="0">
    <value>Filter Table</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0016I" group="bimlmv" key="KEY_PREV_PAGE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3101472966" valuecrc="2315996464" explanationcrc="0" responsecrc="0">
    <value>Previous Page</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0017I" group="bimlmv" key="KEY_NEXT_PAGE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="595195049" valuecrc="1943755385" explanationcrc="0" responsecrc="0">
    <value>Next Page</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0018I" group="bimlmv" key="KEY_CLOSE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1374514136" valuecrc="3535843008" explanationcrc="0" responsecrc="0">
    <value>Close</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0019I" group="bimlmv" key="KEY_ASSET_PROP_TITLE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3393726391" valuecrc="3445905987" explanationcrc="0" responsecrc="0">
    <value>Asset : {0}</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0020I" group="bimlmv" key="KEY_DASH" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3928715752" valuecrc="2547889144" explanationcrc="0" responsecrc="0">
    <value>-</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0021W" group="bimlmv" key="uploding-model-file" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2366558794" valuecrc="2912526792" explanationcrc="0" responsecrc="0">
    <value>Uploading model file</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0022I" group="bimlmv" key="bytes-to-upload" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="101773175" valuecrc="3969522389" explanationcrc="0" responsecrc="0">
    <value>{0} bytes</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0023W" group="bimlmv" key="bucket_not_found" prefix="false" options_value="33" displaymethod="MSGBOX" otherscrc="109184933" valuecrc="2211310702" explanationcrc="0" responsecrc="0">
    <value>Bucket {0} was not found for user key {1}</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0024W" group="bimlmv" key="model_not_found" prefix="false" options_value="33" displaymethod="MSGBOX" otherscrc="2642610367" valuecrc="2388325765" explanationcrc="0" responsecrc="0">
    <value>Model {0} was not found</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0025I" group="bimlmv" key="submit-auto-registration" prefix="false" options_value="1" displaymethod="TEXT" otherscrc="1340616520" valuecrc="556130353" explanationcrc="0" responsecrc="0">
    <value>Model {0} submitted for registration.  Use the Manage Viewables dialog to check its status</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0026I" group="bimlmv" key="upload-complete" prefix="false" options_value="1" displaymethod="TEXT" otherscrc="947322296" valuecrc="682125991" explanationcrc="0" responsecrc="0">
    <value>Upload of model complete</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0027W" group="bimlmv" key="viewable_not_found" prefix="false" options_value="33" displaymethod="MSGBOX" otherscrc="2365481670" valuecrc="1159902278" explanationcrc="0" responsecrc="0">
    <value>Viewable {0} was not found</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0028I" group="bimlmv" key="DLG_TT_SAVE_VIEW" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3961980694" valuecrc="2558122247" explanationcrc="0" responsecrc="0">
    <value>Save View...</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0029I" group="bimlmv" key="DLG_TT_APPLY_VIEW" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2005027705" valuecrc="1036388316" explanationcrc="0" responsecrc="0">
    <value>Apply Saved View...</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0030I" group="bimlmv" key="DLG_LABEL_SAVE_VIEW" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="935176301" valuecrc="3629925992" explanationcrc="0" responsecrc="0">
    <value>Save View</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0031I" group="bimlmv" key="DLG_LABEL_APPLY_VIEW" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2887312386" valuecrc="2886596829" explanationcrc="0" responsecrc="0">
    <value>Apply Saved View</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0032I" group="bimlmv" key="DLG_BTN_APPLY" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3683006194" valuecrc="2096014107" explanationcrc="0" responsecrc="0">
    <value>Apply</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0033I" group="bimlmv" key="DLG_TITLE_SAVE_VIEW" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1076066973" valuecrc="1375201558" explanationcrc="0" responsecrc="0">
    <value>Save Current View</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0034I" group="bimlmv" key="DLG_TITLE_APPLY_VIEW" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="884708114" valuecrc="2741684541" explanationcrc="0" responsecrc="0">
    <value>Select View to Restore</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0035I" group="bimlmv" key="DLG_BTN_DELETE_VIEW" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2938036093" valuecrc="1619625620" explanationcrc="0" responsecrc="0">
    <value>Delete Saved View</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0036W" group="bimlmv" key="MSG_TITLE_REQUIRED_FIELD" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="604037696" valuecrc="3995031000" explanationcrc="0" responsecrc="0">
    <value>Required Field Missing %1</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0037I" group="bimlmv" key="DLG_BTN_CREATE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1126515170" valuecrc="2289755597" explanationcrc="0" responsecrc="0">
    <value>Create</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0038I" group="bimlmv" key="DLG_BTN_CANCEL" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="833740435" valuecrc="1371193412" explanationcrc="0" responsecrc="0">
    <value>Cancel</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0039I" group="bimlmv" key="DLG_BTN_OK" prefix="false" options_value="0" displaymethod="STATUS" otherscrc="3219905522" valuecrc="3610695981" explanationcrc="0" responsecrc="0">
    <value>OK</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0040I" group="bimlmv" key="MAP_BTN_MODELLIST" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1255058997" valuecrc="1616193707" explanationcrc="0" responsecrc="0">
    <value>Display Model List</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0041I" group="bimlmv" key="DLG_BTN_LOCATE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3513508442" valuecrc="3291962359" explanationcrc="0" responsecrc="0">
    <value>Locate</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0042I" group="bimlmv" key="MSG_NOT_ASSET" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2801086634" valuecrc="3942567151" explanationcrc="0" responsecrc="0">
    <value>The current selection is not a Maximo asset</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0043E" group="bimlmv" key="ERR_NO_GUID" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="927657474" valuecrc="1158546024" explanationcrc="0" responsecrc="0">
    <value>The selected item doesn&apos;t have a unique identifier.  It may be necessary to define a binding in the Manage Building Models application</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0044I" group="bimlmv" key="DLG_BTN_VIEW" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1237882186" valuecrc="1590625456" explanationcrc="0" responsecrc="0">
    <value>View</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0045I" group="bimlmv" key="KEY_LOCATION_PROP_TITLE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3530414373" valuecrc="1250478697" explanationcrc="0" responsecrc="0">
    <value>Location: {0}</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0046I" group="bimlmv" key="CAT_ADDRESS" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2784168917" valuecrc="3270727197" explanationcrc="0" responsecrc="0">
    <value>Address</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0047I" group="bimlmv" key="CAT_COST" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1045841850" valuecrc="1859942572" explanationcrc="0" responsecrc="0">
    <value>Costs</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0048I" group="bimlmv" key="CAT_BASE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1287837899" valuecrc="2373751796" explanationcrc="0" responsecrc="0">
    <value>Basic Information</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0049I" group="bimlmv" key="CAT_DETAIL" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3613889700" valuecrc="3181064726" explanationcrc="0" responsecrc="0">
    <value>Details</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0050I" group="bimlmv" key="CAT_DOWN" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2539157424" valuecrc="1487844190" explanationcrc="0" responsecrc="0">
    <value>Down Time</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0051I" group="bimlmv" key="CAT_FACILITY" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="217922527" valuecrc="3803547141" explanationcrc="0" responsecrc="0">
    <value>Facilities</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0052I" group="bimlmv" key="CAT_MODIFY" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2070145327" valuecrc="2786922234" explanationcrc="0" responsecrc="0">
    <value>Modified</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0053I" group="bimlmv" key="CAT_PURCHASE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3771114816" valuecrc="2558181667" explanationcrc="0" responsecrc="0">
    <value>Purchase Information</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0054I" group="bimlmv" key="CAT_OTHER" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2489208015" valuecrc="412686884" explanationcrc="0" responsecrc="0">
    <value>Other</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0055I" group="bimlmv" key="CAT_SPEC" prefix="false" options_value="0" displaymethod="MSGBOX" otherscrc="640123547" valuecrc="3334402707" explanationcrc="0" responsecrc="0">
    <value>Specifications</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0056I" group="bimlmv" key="KEY_PROP_LOADIN_MSG" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2019938896" valuecrc="3679747588" explanationcrc="0" responsecrc="0">
    <value>Loading properties...</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0057I" group="bimlmv" key="KEY_ERROR" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3821051455" valuecrc="2619118453" explanationcrc="0" responsecrc="0">
    <value>Error</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0058I" group="bimlmv" key="KEY_ATTACHMENT" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2438201678" valuecrc="1102343646" explanationcrc="0" responsecrc="0">
    <value>Attachments for {0}</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0059I" group="bimlmv" key="KEY_CLASS_STRUCT" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="183586081" valuecrc="1560353147" explanationcrc="0" responsecrc="0">
    <value>Hierarchy Path</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0060I" group="bimlmv" key="KEY_DISABLE_AUTO_ZOOM" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="714218366" valuecrc="318864950" explanationcrc="0" responsecrc="0">
    <value>Disable Auto Zoom</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0061I" group="bimlmv" key="KEY_ENABLE_AUTO_ZOOM" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2973194001" valuecrc="275432211" explanationcrc="0" responsecrc="0">
    <value>Enable Auto Zoom</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0062I" group="bimlmv" key="TOOLBAR_ISOLATE_SELECTION" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3332998625" valuecrc="3682964773" explanationcrc="0" responsecrc="0">
    <value>Isolate Selection</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0063E" group="bimlmv" key="Bad Request" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1461082953" valuecrc="4238210348" explanationcrc="703832646" responsecrc="0">
    <value>{0}: Bad Request</value>
    <explanation>The server cannot or will not process the request due to an apparent client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).</explanation>
    <response></response>
  </message>
  <message id="BIMFV0064E" group="bimlmv" key="Unauthorized" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="596554438" valuecrc="1551996639" explanationcrc="650966126" responsecrc="0">
    <value>{0}: Unauthorized</value>
    <explanation>Similar to 403 Forbidden, but specifically for use when authentication is required and has failed or has not yet been provided. The response must include a WWW-Authenticate header field containing a challenge applicable to the requested resource. See Basic access authentication and Digest access authentication.[37] 401 semantically means &quot;unauthenticated&quot;,[38] i.e. the user does not have the necessary credentials.Note: Some sites issue HTTP 401 when an IP address is banned from the website (usually the website domain) and that specific address is refused permission to access a website.</explanation>
    <response></response>
  </message>
  <message id="BIMFV0065E" group="bimlmv" key="Payment Required" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3089890985" valuecrc="1082938554" explanationcrc="2846699966" responsecrc="0">
    <value>{0}: Payment Required</value>
    <explanation>Reserved for future use. The original intention was that this code might be used as part of some form of digital cash or micropayment scheme, but that has not happened, and this code is not usually used.</explanation>
    <response></response>
  </message>
  <message id="BIMFV0066E" group="bimlmv" key="Forbidden" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3484757081" valuecrc="190377714" explanationcrc="3378862412" responsecrc="0">
    <value>{0}: Forbidden</value>
    <explanation>The request was a valid request, but the server is refusing to respond to it. 403 error semantically means &quot;unauthorized&quot;, i.e. the user does not have the necessary permissions for the resource</explanation>
    <response></response>
  </message>
  <message id="BIMFV0067E" group="bimlmv" key="Not Found" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1410359350" valuecrc="462755057" explanationcrc="1352942923" responsecrc="0">
    <value>{0}: Not Found</value>
    <explanation>The requested resource could not be found but may be available in the future. Subsequent requests by the client are permissible</explanation>
    <response></response>
  </message>
  <message id="BIMFV0068E" group="bimlmv" key="Method Not Allowed" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="646250311" valuecrc="1024261039" explanationcrc="2793599822" responsecrc="0">
    <value>{0}: Method Not Allowed</value>
    <explanation>A request method is not supported for the requested resource; for example, a GET request on a form which requires data to be presented via POST, or a PUT request on a read-only resource.</explanation>
    <response></response>
  </message>
  <message id="BIMFV0069E" group="bimlmv" key="Not Acceptable" prefix="true" options_value="0" displaymethod="TEXT" otherscrc="1802103225" valuecrc="2231161541" explanationcrc="819293027" responsecrc="0">
    <value>{0}; Not Acceptable</value>
    <explanation>The requested resource is capable of generating only content not acceptable according to the Accept headers sent in the request.[</explanation>
    <response></response>
  </message>
  <message id="BIMFV0070E" group="bimlmv" key="Proxy Authentication Required" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="4246622268" valuecrc="1972138290" explanationcrc="934419586" responsecrc="0">
    <value>{0}: Proxy Authentication Required</value>
    <explanation>The client must first authenticate itself with the proxy.</explanation>
    <response></response>
  </message>
  <message id="BIMFV0071E" group="bimlmv" key="Request Timeout" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1723538515" valuecrc="2940191439" explanationcrc="1147895945" responsecrc="0">
    <value>{0}: Request Timeout</value>
    <explanation>The server timed out waiting for the request. According to HTTP specifications: &quot;The client did not produce a request within the time that the server was prepared to wait. The client MAY repeat the request without modifications at any later time.&quot;[</explanation>
    <response></response>
  </message>
  <message id="BIMFV0072E" group="bimlmv" key="Conflict" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="287690403" valuecrc="1607998615" explanationcrc="512867497" responsecrc="0">
    <value>{0}: Conflict</value>
    <explanation>Indicates that the request could not be processed because of conflict in the request, such as an edit conflict between multiple simultaneous updates.</explanation>
    <response></response>
  </message>
  <message id="BIMFV0073E" group="bimlmv" key="Gone" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2323677900" valuecrc="2068029336" explanationcrc="2244842256" responsecrc="0">
    <value>{0}: Gone</value>
    <explanation>Indicates that the resource requested is no longer available and will not be available again. This should be used when a resource has been intentionally removed and the resource should be purged. Upon receiving a 410 status code, the client should not request the resource in the future. Clients such as search engines should remove the resource from their indices.[44] Most use cases do not require clients and search engines to purge the resource, and a &quot;404 Not Found&quot; may be used instead.</explanation>
    <response></response>
  </message>
  <message id="BIMFV0074E" group="bimlmv" key="Length Required" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="4263013187" valuecrc="3168525575" explanationcrc="953657631" responsecrc="0">
    <value>{0}: Length Required</value>
    <explanation>The request did not specify the length of its content, which is required by the requested resource.</explanation>
    <response></response>
  </message>
  <message id="BIMFV0075E" group="bimlmv" key="Precondition Failed" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1706895148" valuecrc="2125543408" explanationcrc="2347719462" responsecrc="0">
    <value>{0}: Precondition Failed</value>
    <explanation>The server does not meet one of the preconditions that the requester put on the request.[</explanation>
    <response></response>
  </message>
  <message id="BIMFV0076E" group="bimlmv" key="Payload Too Large" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="304346588" valuecrc="1336792528" explanationcrc="487921398" responsecrc="0">
    <value>{0}: Payload Too Large</value>
    <explanation>The request is larger than the server is willing or able to process. Previously called &quot;Request Entity Too Large&quot;.[</explanation>
    <response></response>
  </message>
  <message id="BIMFV0077E" group="bimlmv" key="URI Too Long" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2307307955" valuecrc="2470477452" explanationcrc="875754951" responsecrc="0">
    <value>{0}: URI Too Long</value>
    <explanation>The URI provided was too long for the server to process. Often the result of too much data being encoded as a query-string of a GET request, in which case it should be converted to a POST request.[48] Called &quot;Request-URI Too Long&quot; previously.[</explanation>
    <response></response>
  </message>
  <message id="BIMFV0078E" group="bimlmv" key="Unsupported Media Type" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="4212270786" valuecrc="3639574379" explanationcrc="3060028091" responsecrc="0">
    <value>{0}: Unsupported Media Type</value>
    <explanation>The request entity has a media type which the server or resource does not support. For example, the client uploads an image as image/svg+xml, but the server requires that images use a different format.</explanation>
    <response></response>
  </message>
  <message id="BIMFV0079E" group="bimlmv" key="Expectation Failed" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1622633133" valuecrc="4009445272" explanationcrc="1874689072" responsecrc="0">
    <value>Expectation Failed</value>
    <explanation>The server cannot meet the requirements of the Expect request-header field.[</explanation>
    <response></response>
  </message>
  <message id="BIMFV0080E" group="bimlmv" key="Range Not Satisfiable" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3664676105" valuecrc="187027742" explanationcrc="1550787230" responsecrc="0">
    <value>{0}: Range Not Satisfiable</value>
    <explanation>The client has asked for a portion of the file (byte serving), but the server cannot supply that portion. For example, if the client asked for a part of the file that lies beyond the end of the file.[50] Called &quot;Requested Range Not Satisfiable&quot; previously.</explanation>
    <response></response>
  </message>
  <message id="BIMFV0081E" group="bimlmv" key="Misdirected Request" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1103874406" valuecrc="3075265643" explanationcrc="1184550690" responsecrc="0">
    <value>{0}: Misdirected Request</value>
    <explanation>The request was directed at a server that is not able to produce a response (for example because a connection reuse).</explanation>
    <response></response>
  </message>
  <message id="BIMFV0082E" group="bimlmv" key="Unprocessable Entity" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="911547286" valuecrc="1338946516" explanationcrc="3942528076" responsecrc="0">
    <value>{0}: Unprocessable Entity</value>
    <explanation>The request was well-formed but was unable to be followed due to semantic errors.[</explanation>
    <response></response>
  </message>
  <message id="BIMFV0083E" group="bimlmv" key="Locked" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2918209529" valuecrc="1486346444" explanationcrc="1457042020" responsecrc="0">
    <value>{0}: Locked</value>
    <explanation>The resource that is being accessed is locked.[</explanation>
    <response></response>
  </message>
  <message id="BIMFV0084E" group="bimlmv" key="Upgrade Required" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3647520374" valuecrc="3503775269" explanationcrc="571291135" responsecrc="0">
    <value>{0}: Upgrade Required</value>
    <explanation>The client should switch to a different protocol such as TLS/1.0, given in the Upgrade header field.</explanation>
    <response></response>
  </message>
  <message id="BIMFV0085E" group="bimlmv" key="Failed Dependency" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1120793113" valuecrc="2981775410" explanationcrc="4273222647" responsecrc="0">
    <value>{0}: Failed Dependency</value>
    <explanation>The request failed due to failure of a previous request (e.g., a PROPPATCH).[</explanation>
    <response></response>
  </message>
  <message id="BIMFV0086E" group="bimlmv" key="Request Header Fields Too Large" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="894640361" valuecrc="851521105" explanationcrc="3570301039" responsecrc="0">
    <value>{0}: Request Header Fields Too Large</value>
    <explanation>The server is unwilling to process the request because either an individual header field, or all the header fields collectively, are too large.[</explanation>
    <response></response>
  </message>
  <message id="BIMFV0087E" group="bimlmv" key="Precondition Required" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2935385222" valuecrc="1664818402" explanationcrc="2088257452" responsecrc="0">
    <value>{0}: Precondition Required</value>
    <explanation>The origin server requires the request to be conditional. Intended to prevent &quot;the &apos;lost update&apos; problem, where a client GETs a resource&apos;s state, modifies it, and PUTs it back to the server, when meanwhile a third party has modified the state on the server, leading to a conflict.&quot;[</explanation>
    <response></response>
  </message>
  <message id="BIMFV0088E" group="bimlmv" key="Too Many Requests" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3697472503" valuecrc="49324368" explanationcrc="1167096907" responsecrc="0">
    <value>{0}: Too Many Requests</value>
    <explanation>The user has sent too many requests in a given amount of time. Intended for use with rate limiting schemes.[</explanation>
    <response></response>
  </message>
  <message id="BIMFV0089E" group="bimlmv" key="Unavailable For Legal Reasons" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1204273048" valuecrc="154318506" explanationcrc="1911759502" responsecrc="0">
    <value>{0}: Unavailable For Legal Reasons</value>
    <explanation>A server operator has received a legal demand to deny access to a resource or to a set of resources that includes the requested resource.[58] The code 451 was chosen as a reference to the novel Fahrenheit 451</explanation>
    <response></response>
  </message>
  <message id="BIMFV0090E" group="bimlmv" key="Internal Server Error" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="133717132" valuecrc="4075383647" explanationcrc="125273906" responsecrc="0">
    <value>{0}: Internal Server Error</value>
    <explanation>A generic error message, given when an unexpected condition was encountered and no more specific message is suitable.[</explanation>
    <response></response>
  </message>
  <message id="BIMFV0091E" group="bimlmv" key="Not Implemented" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2623344867" valuecrc="1722152065" explanationcrc="593337038" responsecrc="0">
    <value>{0}: Not Implemented</value>
    <explanation>The server either does not recognize the request method, or it lacks the ability to fulfill the request. Usually this implies future availability (e.g., a new feature of a web-service API).</explanation>
    <response></response>
  </message>
  <message id="BIMFV0092E" group="bimlmv" key="Bad Gateway" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3955474963" valuecrc="3556026316" explanationcrc="0" responsecrc="0">
    <value>{0}: Bad Gateway</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0093E" group="bimlmv" key="Service Unavailable" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1885769340" valuecrc="455092241" explanationcrc="2790154279" responsecrc="0">
    <value>{0}: Service Unavailable</value>
    <explanation>The server is currently unavailable (because it is overloaded or down for maintenance). Generally, this is a temporary state.</explanation>
    <response></response>
  </message>
  <message id="BIMFV0094E" group="bimlmv" key="Gateway Timeout" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="83781619" valuecrc="4107270519" explanationcrc="655799916" responsecrc="0">
    <value>{0}: Gateway Timeout</value>
    <explanation>The server was acting as a gateway or proxy and did not receive a timely response from the upstream server.[</explanation>
    <response></response>
  </message>
  <message id="BIMFV0095E" group="bimlmv" key="HTTP Version Not Supported" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2673552284" valuecrc="1189608061" explanationcrc="2024016244" responsecrc="0">
    <value>{0}: HTTP Version Not Supported</value>
    <explanation>The server does not support the HTTP protocol version used in the request.</explanation>
    <response></response>
  </message>
  <message id="BIMFV0096E" group="bimlmv" key="Variant Also Negotiates" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3905288556" valuecrc="556002941" explanationcrc="2020717548" responsecrc="0">
    <value>{0}: Variant Also Negotiates</value>
    <explanation>Transparent content negotiation for the request results in a circular reference.[</explanation>
    <response></response>
  </message>
  <message id="BIMFV0097E" group="bimlmv" key="Insufficient Storage" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1935717635" valuecrc="2379980119" explanationcrc="284462337" responsecrc="0">
    <value>{0}: Insufficient Storage</value>
    <explanation>The server is unable to store the representation needed to complete the request.[</explanation>
    <response></response>
  </message>
  <message id="BIMFV0098E" group="bimlmv" key="Loop Detected" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="32778866" valuecrc="2308750046" explanationcrc="3487757507" responsecrc="0">
    <value>{0} Loop Detected</value>
    <explanation>The server detected an infinite loop while processing the request (sent in lieu of 208 Already Reported).</explanation>
    <response></response>
  </message>
  <message id="BIMFV0099E" group="bimlmv" key="Not Extended" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2589025821" valuecrc="130059868" explanationcrc="117130339" responsecrc="0">
    <value>{0}: Not Extended</value>
    <explanation>Further extensions to the request are required for the server to fulfil it.[</explanation>
    <response></response>
  </message>
  <message id="BIMFV0100E" group="bimlmv" key="Network Authentication Required" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="493008658" valuecrc="2257368832" explanationcrc="1862852434" responsecrc="0">
    <value>{0}: Network Authentication Required</value>
    <explanation>The client needs to authenticate to gain network access. Intended for use by intercepting proxies used to control access to the network (e.g., &quot;captive portals&quot; used to require agreement to Terms of Service before granting full Internet access via a Wi-Fi hotspot).[</explanation>
    <response></response>
  </message>
  <message id="BIMFV0101E" group="bimlmv" key="ERR_REST" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2261252989" valuecrc="2614042772" explanationcrc="0" responsecrc="0">
    <value>REST Error</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0102I" group="bimlmv" key="KEY_PARENT" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="4215520074" valuecrc="975332729" explanationcrc="0" responsecrc="0">
    <value>Parent</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0103I" group="bimlmv" key="KEY_WO_PROP_TITLE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1625749285" valuecrc="2233612387" explanationcrc="0" responsecrc="0">
    <value>Work Order: {0}</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0104I" group="bimlmv" key="KEY_COMPANY_PROP_TITLE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="343809706" valuecrc="581891530" explanationcrc="0" responsecrc="0">
    <value>Company: {0}</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0105I" group="bimlmv" key="KEY_PRODUCT_PROP_TITLE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2413515461" valuecrc="3962293637" explanationcrc="0" responsecrc="0">
    <value>Product: {0}</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0106I" group="bimlmv" key="DLG_TXT_DELETE_VIEW" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="4165304373" valuecrc="2414226042" explanationcrc="0" responsecrc="0">
    <value>Delete saved view</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0107I" group="bimlmv" key="bucket-delete-not-allowed" prefix="false" options_value="1" displaymethod="MSGBOX" otherscrc="4241580696" valuecrc="1102024741" explanationcrc="0" responsecrc="0">
    <value>You must select \&quot;Delete All Models\&quot; and \&quot;Delete All Viewables\&quot; before you can delete the storage container</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0108I" group="bimlmv" key="model-confirm-overwrite" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="292836139" valuecrc="3720407273" explanationcrc="0" responsecrc="0">
    <value>The file {1} exists in storage container {2}.  Do you want to overwrite it?</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0109I" group="bimlmv" key="DLG_TITLE_SAVE_MARKUP" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2328960836" valuecrc="4036804493" explanationcrc="0" responsecrc="0">
    <value>Save Markup</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0110I" group="bimlmv" key="DLG_TITLE_CONFIRM_DELETE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3404659792" valuecrc="1198184422" explanationcrc="0" responsecrc="0">
    <value>Confirm Delete</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0111I" group="bimlmv" key="DLG_TITLE_DISPLAY_MARKUP" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1363914815" valuecrc="3241338180" explanationcrc="0" responsecrc="0">
    <value>Display Markup</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0112I" group="bimlmv" key="DLG_TITLE_MARKUP_STYLE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="651518671" valuecrc="1407408591" explanationcrc="0" responsecrc="0">
    <value>Markup Style</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0113I" group="bimlmv" key="DLG_BTN_DELETE_MARKUP" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3178245792" valuecrc="3307577312" explanationcrc="0" responsecrc="0">
    <value>Delete Markup</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0114I" group="bimlmv" key="DLG_LABEL_MARKUP_DESC" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3387475759" valuecrc="1384422821" explanationcrc="0" responsecrc="0">
    <value>Markup Description</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0115I" group="bimlmv" key="DLG_LABEL_LINE_WEIGHT" prefix="false" options_value="0" displaymethod="MSGBOX" otherscrc="36927081" valuecrc="3901958623" explanationcrc="0" responsecrc="0">
    <value>Line Weight</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0116I" group="bimlmv" key="DLG_LABLE_FILL" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="634608048" valuecrc="1433477514" explanationcrc="0" responsecrc="0">
    <value>Fill</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0117I" group="bimlmv" key="DLG_LABLE_FONT_SIZE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3195409887" valuecrc="3188186903" explanationcrc="0" responsecrc="0">
    <value>Font Size</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0118I" group="bimlmv" key="DLG_LABLE_ITALICS" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3437398702" valuecrc="3375652360" explanationcrc="0" responsecrc="0">
    <value>Italics</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0119I" group="bimlmv" key="DLG_LABLE_BOLD" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1464321729" valuecrc="3494199901" explanationcrc="0" responsecrc="0">
    <value>Bold</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0120I" group="bimlmv" key="MSG_CONFIRM_DELETE_MAKRUP" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1998885022" valuecrc="1881222760" explanationcrc="0" responsecrc="0">
    <value>Delete markup {0}?</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0121I" group="bimlmv" key="MARKUP_START_EDIT" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3967933681" valuecrc="193980772" explanationcrc="0" responsecrc="0">
    <value>Enter markup mode</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0122I" group="bimlmv" key="MARKUP_CANCEL" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2602503681" valuecrc="962155932" explanationcrc="0" responsecrc="0">
    <value>Cancel markup mode</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0123I" group="bimlmv" key="MARKUP_SAVE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="12206702" valuecrc="81847860" explanationcrc="0" responsecrc="0">
    <value>Save markup with work order...</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0124I" group="bimlmv" key="MARKUP_SHOW" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1948429281" valuecrc="2314531759" explanationcrc="0" responsecrc="0">
    <value>Show Markup...</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0125I" group="bimlmv" key="MARKUP_ARROW" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="4018661262" valuecrc="3205095150" explanationcrc="0" responsecrc="0">
    <value>Select arrow markup tool</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0126I" group="bimlmv" key="MARKUP_CLOUD" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2551788926" valuecrc="2830387132" explanationcrc="0" responsecrc="0">
    <value>Select cloud markup tool</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0127I" group="bimlmv" key="MARKUP_FREEHAND" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="62683409" valuecrc="4003344406" explanationcrc="0" responsecrc="0">
    <value>Select freehand markup tool</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0128I" group="bimlmv" key="MARKUP_LINE" prefix="true" options_value="0" displaymethod="TEXT" otherscrc="1850422285" valuecrc="411129746" explanationcrc="0" responsecrc="0">
    <value>Select line markup tool</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0129I" group="bimlmv" key="MARKUP_OVAL" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3935152655" valuecrc="4037149100" explanationcrc="0" responsecrc="0">
    <value>Select oval markup tool</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0130I" group="bimlmv" key="MARKUP_RECTANGLE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2863810843" valuecrc="1381425045" explanationcrc="0" responsecrc="0">
    <value>Select rectangle markup tool</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0131I" group="bimlmv" key="MARKUP_TEXT" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="823592308" valuecrc="1067538210" explanationcrc="0" responsecrc="0">
    <value>Select text markup tool</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0132I" group="bimlmv" key="NAKRUP_RED" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="1183438724" valuecrc="257488027" explanationcrc="0" responsecrc="0">
    <value>R:</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0133I" group="bimlmv" key="MAKRUP_GREEN" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="3710688235" valuecrc="955060879" explanationcrc="0" responsecrc="0">
    <value>G:</value>
    <explanation></explanation>
    <response></response>
  </message>
  <message id="BIMFV0134I" group="bimlmv" key="MARKUP_BLUE" prefix="false" options_value="0" displaymethod="TEXT" otherscrc="2847175268" valuecrc="1167779530" explanationcrc="0" responsecrc="0">
    <value>B:</value>
    <explanation></explanation>
    <response></response>
  </message>
</messages>
